### ISSUE TITLE
device sync from android to windows 10 machine

### ISSUE THREAD

**Issue by frendcarlo** [datalogic/device-sync#2]
Is there any for android OS to windows 10 machine?

**Comment by codybrookshear** [comment]
We haven't developed such a tool for Android since `adb` is available and works well. 

https://developer.android.com/studio/command-line/adb

**Comment by pcdejong1980** [comment]
> Is there any for android OS to windows 10 machine?

See for example this batch file: https://my.syncplicity.com/share/albrmhkfmgc3sgn/Datalogic_Android_Stage_4.1

You can use this batch file that is using adb to install firmware, copy files and install apk's on a Datalogic Android terminal. 

(This is an non-official tool and is not officially supported)

**Comment by codybrookshear** [comment]
thanks Peter! (@pcdejong1980 )
